comments:
  UndocumentedPublicClass:
    active: true
    excludes: ["**/src/test/**"]
    ignoreDefaultCompanionObject: true
  UndocumentedPublicFunction:
    active: true
    excludes: ["**/src/test/**"]
  UndocumentedPublicProperty:
    active: true
    excludes: ["**/src/test/**"]
